-- Migration: 0001_m01_foundation
-- Purpose: Establish the M01/M02-ready PostgreSQL tenant foundation for
-- users, organizations, memberships, projects, and append-only audit events.
--
-- Forward procedure:
--   1. Verify the target and a current backup/PITR recovery point.
--   2. Run the package migration runner with DATABASE_URL supplied through the
--      protected process environment.
--   3. Verify the five tables, constraints, indexes, and audit triggers.
--
-- Recovery guidance:
--   This is a forward-only production migration. If the application rollout
--   fails after this additive migration, roll back the application and retain
--   the compatible tables. Correct schema defects with a reviewed forward
--   migration. Restore from a verified backup/PITR point only through the
--   separately approved database recovery runbook. Tables may be dropped in
--   reverse dependency order only in a disposable local/test database after
--   confirming it contains no retained evidence.

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY NOT NULL,
  "identity_provider_id" text NOT NULL,
  "display_name" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "users_identity_provider_id_unique" UNIQUE ("identity_provider_id"),
  CONSTRAINT "users_status_check" CHECK ("status" IN ('active', 'suspended', 'disabled'))
);
--> statement-breakpoint
COMMENT ON COLUMN "users"."id" IS 'Application-generated UUID; never generated by the database';
--> statement-breakpoint
CREATE TABLE "organizations" (
  "id" uuid PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "policy_profile_id" uuid,
  "status" text DEFAULT 'active' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "organizations_slug_unique" UNIQUE ("slug"),
  CONSTRAINT "organizations_status_check" CHECK ("status" IN ('active', 'suspended', 'archived'))
);
--> statement-breakpoint
COMMENT ON COLUMN "organizations"."id" IS 'Application-generated UUID; never generated by the database';
--> statement-breakpoint
CREATE TABLE "memberships" (
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "memberships_organization_id_user_id_pk" PRIMARY KEY ("organization_id", "user_id"),
  CONSTRAINT "memberships_role_check" CHECK ("role" IN ('owner', 'developer', 'designer', 'reviewer', 'viewer')),
  CONSTRAINT "memberships_organization_id_organizations_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id")
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "memberships_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "users"("id")
    ON DELETE RESTRICT ON UPDATE RESTRICT
);
--> statement-breakpoint
CREATE INDEX "memberships_user_id_idx" ON "memberships" ("user_id");
--> statement-breakpoint
CREATE TABLE "projects" (
  "id" uuid PRIMARY KEY NOT NULL,
  "organization_id" uuid NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "plugin_type" text DEFAULT 'website' NOT NULL,
  "policy_id" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "projects_organization_id_slug_unique" UNIQUE ("organization_id", "slug"),
  CONSTRAINT "projects_organization_id_id_unique" UNIQUE ("organization_id", "id"),
  CONSTRAINT "projects_status_check" CHECK ("status" IN ('active', 'archived', 'deletion_pending', 'deleted')),
  CONSTRAINT "projects_organization_id_organizations_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id")
    ON DELETE RESTRICT ON UPDATE RESTRICT
);
--> statement-breakpoint
COMMENT ON COLUMN "projects"."id" IS 'Application-generated UUID; never generated by the database';
--> statement-breakpoint
CREATE INDEX "projects_organization_id_status_idx" ON "projects" ("organization_id", "status");
--> statement-breakpoint
CREATE TABLE "audit_events" (
  "id" uuid PRIMARY KEY NOT NULL,
  "schema_version" text DEFAULT '1' NOT NULL,
  "organization_id" uuid NOT NULL,
  "project_id" uuid,
  "actor_ref" text NOT NULL,
  "action" text NOT NULL,
  "target_ref" text NOT NULL,
  "outcome" text NOT NULL,
  "correlation_id" uuid NOT NULL,
  "payload_ref" text,
  "occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "audit_events_organization_id_organizations_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id")
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "audit_events_project_tenant_fk"
    FOREIGN KEY ("organization_id", "project_id")
    REFERENCES "projects"("organization_id", "id")
    ON DELETE RESTRICT ON UPDATE RESTRICT
);
--> statement-breakpoint
COMMENT ON COLUMN "audit_events"."id" IS 'Application-generated UUID; never generated by the database';
--> statement-breakpoint
CREATE INDEX "audit_events_organization_id_occurred_at_idx"
  ON "audit_events" ("organization_id", "occurred_at");
--> statement-breakpoint
CREATE INDEX "audit_events_project_id_occurred_at_idx"
  ON "audit_events" ("project_id", "occurred_at");
--> statement-breakpoint
CREATE INDEX "audit_events_correlation_id_idx"
  ON "audit_events" ("correlation_id");
--> statement-breakpoint
CREATE FUNCTION "reject_audit_event_mutation"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only; append a correction event instead'
    USING ERRCODE = '55000';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "audit_events_reject_update_or_delete"
BEFORE UPDATE OR DELETE ON "audit_events"
FOR EACH ROW
EXECUTE FUNCTION "reject_audit_event_mutation"();
--> statement-breakpoint
CREATE TRIGGER "audit_events_reject_truncate"
BEFORE TRUNCATE ON "audit_events"
FOR EACH STATEMENT
EXECUTE FUNCTION "reject_audit_event_mutation"();
